installation:
  cni:
    type: Calico
    ipam:
      type: HostLocal
  calicoNetwork:
    bgp: Disabled
    mtu: 1350
    ipPools:
    - blockSize: 122
      cidr: 2001:1234:5678:9a40::/58
      encapsulation: None
      natOutgoing: Enabled
      nodeSelector: all()
  registry: mcr.microsoft.com/oss
  tag: v3.25.1
# Image and registry configuration for the tigera/operator pod.
tigeraOperator:
  image: tigera/operator
  registry: mcr.microsoft.com/oss
  tag: v1.29.3
calicoctl:
  image: mcr.microsoft.com/oss/calico/ctl
  tag: v3.25.1
